version: "5.0.2"

services:
  web:
    build: ./app
    container_name: web_app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=testdb
      - REDIS_HOST=redis
    networks:
      - app-network
    labels:
      - "project=day34"
      - "tier=frontend"

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    labels:
      - "project=day34"
      - "tier=database"

  redis:
    image: redis:7
    container_name: redis_cache
    networks:
      - app-network
    labels:
      - "project=day34"
      - "tier=cache"

volumes:
  db-data:

networks:
  app-network:
    driver: bridge